services:
  app:
    build: .
    container_name: fast-api
    command: fastapi run app/main.py --port 8000 --host 127.0.0.1 --reload
    ports:
      - 8080:8000
    volumes:
      - .:/app
      - venv:/app/.venv

volumes:
  venv:
